export const listPersonnelValid = {
  page: 'number',
  limit: 'number',
  keySearch: { type: 'string', allowNull: true },
  email: { type: 'string', allowNull: true },
  department: { type: 'string', allowNull: true },
  position: { type: 'string', allowNull: true },
  jobPosition: { type: 'string', allowNull: true },
  status: { type: 'number', allowNull: true }
};

export const detailPersonnelValid = {
  _id: 'string'
};

export const updatePersonnelValid = {
  _id: 'string',
  department: { type: 'string', allowNull: true },
  position: { type: 'string', allowNull: true },
  jobPosition: { type: 'string', allowNull: true },
  staffCode: { type: 'string', allowNull: true },
  fullName: { type: 'string', allowNull: true },
  email: { type: 'email', allowNull: true },
  phone: { type: 'phone', allowNull: true },
  cmt: { type: 'string', allowNull: true },
  dateOfIssue: { type: 'date', allowNull: true },
  placeOfIssue: { type: 'string', allowNull: true },
  gender: { type: 'string', allowNull: true },
  bankAccount: { type: 'string', allowNull: true },
  bank: { type: 'string', allowNull: true },
  salary: { type: 'number', allowNull: true },
  type: { type: 'number', allowNull: true },
  maritalStatus: { type: 'number', allowNull: true },
  nationality: { type: 'string', allowNull: true },
  religion: { type: 'string', allowNull: true },
  address: { type: 'string', allowNull: true },
  permanentAddress: { type: 'string', allowNull: true },
  healthInsuranceNumber: { type: 'string', allowNull: true },
  socialInsuranceNumber: { type: 'string', allowNull: true },
  taxCode: { type: 'string', allowNull: true },
  taxAuth: { type: 'number', allowNull: true },
  qualification: { type: 'number', allowNull: true },
  graduationType: { type: 'number', allowNull: true },
  major: { type: 'string', allowNull: true },
  foreignLanguage: { type: 'string', allowNull: true },
  computerScience: { type: 'string', allowNull: true },
  healthStatus: { type: 'string', allowNull: true },
  pathology: { type: 'string', allowNull: true },
  avatar: { type: 'string', allowNull: true },
  birthday: { type: 'date', allowNull: true },
  dateIn: { type: 'date', allowNull: true },
  contacts: { type: 'json', allowNull: true },
  dependents: { type: 'json', allowNull: true },
  cmtFiles: { type: 'json', allowNull: true },
  taxFiles: { type: 'json', allowNull: true },
  healthFiles: { type: 'json', allowNull: true },
  educationFiles: { type: 'json', allowNull: true },
  status: { type: 'number', allowNull: true },
};

export const createPersonnelValid = {
  department: { type: 'string', allowNull: true },
  position: 'string',
  jobPosition: 'string',
  staffCode: 'string',
  fullName: 'string',
  email: 'email',
  phone: 'phone',
  cmt: 'string',
  dateOfIssue: 'date',
  placeOfIssue: 'string',
  gender: 'string',
  bankAccount: 'string',
  bank: 'string',
  salary: 'number',
  type: 'number',
  maritalStatus: { type: 'number', allowNull: true },
  nationality: 'string',
  religion: { type: 'string', allowNull: true },
  address: 'string',
  permanentAddress: { type: 'string', allowNull: true },
  healthInsuranceNumber: { type: 'string', allowNull: true },
  socialInsuranceNumber: { type: 'string', allowNull: true },
  taxCode: { type: 'string', allowNull: true },
  taxAuth: { type: 'number', allowNull: true },
  qualification: { type: 'number', allowNull: true },
  graduationType: { type: 'number', allowNull: true },
  major: { type: 'string', allowNull: true },
  foreignLanguage: { type: 'string', allowNull: true },
  computerScience: { type: 'string', allowNull: true },
  healthStatus: { type: 'string', allowNull: true },
  pathology: { type: 'string', allowNull: true },
  birthday: 'date',
  dateIn: 'date',
  contacts: { type: 'json', allowNull: true },
  dependents: { type: 'json', allowNull: true },
};
